### PR TITLE
Enhancement: Allow disabling rules

### LINKED ISSUE #518: Rule disable option
Type: feature

Add rules disable functionality. 
From config perpective it could look something like this:

```
ergebnis:
              NoExtendsRule:
                       enable: false

              // then other options to rules could look like this
              FinalRule:
                       allowAbstractClasses: false
                       classesNotRequiredToBeAbstractOrFinal:
			       - Foo\Bar\NeitherAbstractNorFinal
```
                       
This way there is rule options indepencdence

### PR DESCRIPTION
**Pull request by localheinz**
This pull request

- [x] allows disabling rules

Fixes #518.

### CODE REVIEW

**Comment by localheinz** [comment]
How do you feel about this, @enumag and @skyferix?

**Comment by enumag** [comment]
Looks good at first glance. I'll try it on my project tomorrow.

**Comment by ondrejmirtes** [comment]
Looks like the same way the configuration is achieved on phpstan-strict-rules, so I highly support this 😊

**Comment by localheinz** [comment]
Thank you, @enumag and @ondrejmirtes!

**Comment by enumag** [comment]
Tried it on my side and it works like a charm. :) ty!

**Comment by localheinz** [comment]
Thank you, @enumag!

**Pull request merged**
